import pytest
import json
import os

from linkml_runtime.utils.schemaview import SchemaView

from inkind_knowledge_repo.generators.ui_descriptor import UiDescriptorGenerator

SCHEMA_PATH = "src/inkind_knowledge_repo/schema/inkind_knowledge_repo.yaml"


def test_ui_descriptor_generation_basic():
    """generate() now returns exactly one class's descriptor — dispatched
    classes (e.g. ClothingItem, reached via DonationItem's category slot)
    are no longer nested inline; they're separate classes generated by
    separate UiDescriptorGenerator instances (see
    generate_all_ui_descriptors)."""
    gen = UiDescriptorGenerator("src/inkind_knowledge_repo/schema/entities/donation_item.yaml", top_class="DonationItem")
    result = gen.generate()

    assert list(result.keys()) == ["DonationItem"]
    base = result["DonationItem"]
    category_field = next((f for f in base["fields"] if f["name"] == "category"), None)
    assert category_field is not None
    assert "dispatches_to" in category_field
    # DonationItem's dispatch is schema-driven via SortingCategoryEnum's
    # dispatch_to annotations now (uniform with StorageCollection/
    # SortedCollection) — NOT DonationItem's own real ClothingItem subclass,
    # which stays a data-model-only class untouched by UI generation.
    assert category_field["dispatches_to"]["ClothingItem"] == "ClothingPhysicalItemMixin.ui.json"

    clothing_gen = UiDescriptorGenerator(
        "src/inkind_knowledge_repo/schema/entities/donation_item.yaml", top_class="ClothingPhysicalItemMixin"
    )
    clothing = clothing_gen.generate()["ClothingPhysicalItemMixin"]
    demo_field = next((f for f in clothing["fields"] if f["name"] == "demographic"), None)
    assert demo_field is not None
    assert demo_field.get("visible_when", {}).get("lifecycle_state") == ["sorting_in_progress"]

    winter_field = next((f for f in clothing["fields"] if f["name"] == "is_winter_suitable"), None)
    assert winter_field is not None
    assert "auto_set_from" in winter_field
    assert winter_field["auto_set_from"]["season"]["winter"] is True
    assert winter_field["auto_set_from"]["season"]["summer"] is False

    size_field = next((f for f in clothing["fields"] if f["name"] == "size"), None)
    assert size_field is not None
    assert "options_depend_on" in size_field

    assert any(r["id"].startswith("uc-") for r in clothing["rules"])
    assert "ClothingSizeEnum" in clothing["enums"]


def test_ui_descriptor_generation_top_class_any_schema_class():
    gen = UiDescriptorGenerator("src/inkind_knowledge_repo/schema/entities/donation_item.yaml", top_class="ClothingItem")
    result = gen.generate()

    assert "ClothingItem" in result
    assert result["ClothingItem"]["class"] == "ClothingItem"
    assert "DonationItem" not in result
    # ClothingItem is a leaf class in this hierarchy, so no subclass outputs expected
    assert len(result) == 1


def test_ui_descriptor_json_serialization():
    """serialize() writes a single class's own descriptor (unwrapped, not
    nested under its class name) — matches the file-per-class output model
    used by generate_all_ui_descriptors."""
    gen = UiDescriptorGenerator(
        "src/inkind_knowledge_repo/schema/entities/donation_item.yaml",
        top_class="DonationItem"
    )
    result = gen.generate()

    output_dir = "examples/output/"
    gen.serialize(output_dir=output_dir)

    # Descriptor file
    output_file = os.path.join(output_dir, "DonationItem.ui.json")
    assert os.path.exists(output_file)

    with open(output_file, "r", encoding="utf-8") as f:
        parsed = json.load(f)

    assert parsed == result["DonationItem"]
    assert parsed["class"] == "DonationItem"

    # Locale files
    for locale in ("en", "de"):
        labels_file = os.path.join(output_dir, f"labels-{locale}.json")
        assert os.path.exists(labels_file)

        with open(labels_file, "r", encoding="utf-8") as f:
            labels = json.load(f)

        assert isinstance(labels, dict)
        assert len(labels) > 0
        # Every key should be a non-empty string
        assert all(isinstance(k, str) and k for k in labels)
        assert all(isinstance(v, str) and v for v in labels.values())


def test_generate_all_ui_descriptors_full_run_to_examples_output():
    """Full 4-root run (the same invocation the `generate-ui-descriptors` CLI
    entry point performs) into examples/output/ — 4 roots + 16 bare Tier 1 +
    16 shared physical-item files + 2 label files = 38 files, matching the
    real production regeneration workflow."""
    from inkind_knowledge_repo.generators.ui_descriptor import generate_all_ui_descriptors, ROOTS

    schema_path = "src/inkind_knowledge_repo/schema/inkind_knowledge_repo.yaml"
    output_dir = "examples/output/"

    generate_all_ui_descriptors(schema_path, output_dir, roots=ROOTS)

    for root in ROOTS:
        assert os.path.exists(os.path.join(output_dir, f"{root}.ui.json"))

    ui_json_files = [f for f in os.listdir(output_dir) if f.endswith(".ui.json")]
    assert len(ui_json_files) == 36  # 4 roots + 16 bare Tier 1 + 16 shared physical-item files

    for locale in ("en", "de"):
        assert os.path.exists(os.path.join(output_dir, f"labels-{locale}.json"))


def test_generate_all_ui_descriptors():
    """End-to-end orchestration: every root + every shared category file
    gets its own <ClassName>.ui.json, dispatch maps resolve to real files,
    and labels are merged across the whole set."""
    import tempfile
    from inkind_knowledge_repo.generators.ui_descriptor import generate_all_ui_descriptors

    schema_path = "src/inkind_knowledge_repo/schema/inkind_knowledge_repo.yaml"

    with tempfile.TemporaryDirectory() as tmp_dir:
        generate_all_ui_descriptors(schema_path, tmp_dir, roots=("DonationItem",))

        donation_item_path = os.path.join(tmp_dir, "DonationItem.ui.json")
        assert os.path.exists(donation_item_path)
        with open(donation_item_path, encoding="utf-8") as f:
            donation_item = json.load(f)

        category_field = next(f for f in donation_item["fields"] if f["name"] == "category")
        dispatch_map = category_field["dispatches_to"]
        assert len(dispatch_map) == 16

        # Every dispatched file must actually have been written, and be
        # self-describing (its own "class" key matches the target filename).
        for category_value, filename in dispatch_map.items():
            target_path = os.path.join(tmp_dir, filename)
            assert os.path.exists(target_path), f"{filename} (for {category_value}) was not generated"
            with open(target_path, encoding="utf-8") as f:
                target = json.load(f)
            assert target["class"] == filename.removesuffix(".ui.json")

        for locale in ("en", "de"):
            labels_path = os.path.join(tmp_dir, f"labels-{locale}.json")
            assert os.path.exists(labels_path)
            with open(labels_path, encoding="utf-8") as f:
                labels = json.load(f)
            assert "DonationItem" in labels
            assert "ClothingPhysicalItemMixin" in labels


def test_ui_descriptor_donation_item_real_subclasses_still_validate():
    """DonationItem's real concrete subclasses (used by gen-pydantic, not by
    UI-descriptor dispatch after the category descriptor sync work) must
    still carry their own category's *ContextRulesMixin lc-* rules via their
    mixin ancestry, so real data validation isn't regressed by moving lc-*
    rules out of donation_item.yaml and into categories/_context_rules.yaml.

    Tier 3 is one mixin PER CATEGORY (not a single universal mixin — an
    earlier version used one, which caused cross-category rule leakage via
    shared field names like "subcategory"; see _context_rules.yaml's header),
    so each subclass is checked against its own category-specific mixin."""
    sv = SchemaView(SCHEMA_PATH)

    subclass_to_context_mixin = {
        "ClothingItem": "ClothingContextRulesMixin",
        "AccessoriesItem": "AccessoriesContextRulesMixin",
        "FootwearItem": "FootwearContextRulesMixin",
        "FurnitureItem": "FurnitureContextRulesMixin",
        "BeddingTextilesItem": "BeddingContextRulesMixin",
        "HouseholdItem": "HouseholdContextRulesMixin",
        "ElectronicsItem": "ElectronicsContextRulesMixin",
        "ToysItem": "ToysContextRulesMixin",
        "SportsItem": "SportsContextRulesMixin",
        "BooksItem": "BooksContextRulesMixin",
        "StationeryItem": "StationeryContextRulesMixin",
        "PersonalCareItem": "PersonalCareContextRulesMixin",
        "MobilityAidsItem": "MobilityAidsContextRulesMixin",
        "BabyInfantItem": "BabyInfantContextRulesMixin",
        "FoodItem": "FoodContextRulesMixin",
        "OtherItem": "OtherContextRulesMixin",
    }
    for cls, context_mixin in subclass_to_context_mixin.items():
        ancestors = sv.class_ancestors(cls)
        assert context_mixin in ancestors, (
            f"{cls} lost {context_mixin} — real data validation would no "
            f"longer enforce its lc-* rules"
        )
        # No OTHER category's context mixin should leak in.
        other_context_mixins = set(subclass_to_context_mixin.values()) - {context_mixin}
        leaked = other_context_mixins & set(ancestors)
        assert not leaked, f"{cls} unexpectedly carries unrelated context mixins: {leaked}"

        rule_titles = set()
        for ancestor in ancestors:
            ancestor_cls = sv.get_class(ancestor)
            for rule in getattr(ancestor_cls, "rules", []) or []:
                rule_titles.add(rule.title)
        assert any(t.startswith("lc-") for t in rule_titles), (
            f"{cls} has no lc-* rules reachable via its ancestor chain"
        )

    # DemandSignal's bare Tier 1 dispatch targets must NEVER pick up any
    # Tier 3 content, from any category.
    demand_targets = ["ClothingCategory", "FurnitureCategory", "MobilityAidsCategory"]
    all_context_mixins = set(subclass_to_context_mixin.values())
    for cls in demand_targets:
        ancestors = set(sv.class_ancestors(cls))
        leaked = all_context_mixins & ancestors
        assert not leaked, (
            f"{cls} (a DemandSignal dispatch target) unexpectedly carries "
            f"Tier 3 lc-* rules: {leaked}"
        )


def test_ui_descriptor_no_cross_category_rule_leakage():
    """Regression test for a real bug found during implementation: a single
    universal Tier 3 mixin caused lc-* rules from one category to attach to
    same-named fields (e.g. "subcategory") in unrelated categories. Confirm
    Furniture's subcategory field — which has no lc-* rule of its own — never
    picks up a visible_when from Clothing/Baby/Sports's subcategory-required
    rules, which share the same target field name."""
    gen = UiDescriptorGenerator(SCHEMA_PATH, top_class="FurnitureAssessmentMixin")
    furniture = gen.generate()["FurnitureAssessmentMixin"]
    subcategory = next(f for f in furniture["fields"] if f["name"] == "subcategory")
    assert "visible_when" not in subcategory


def test_ui_descriptor_labels_resolve_via_ancestor_walk_from_tier1_mixin():
    """label_en/label_de/aliases_en/aliases_de are declared on each category's
    Tier 1 mixin (e.g. FurnitureCategory) and also mirrored onto DonationItem's
    real concrete subclasses (e.g. FurnitureItem) for alias_generator.py, which
    walks sv.all_classes() directly rather than through the UI descriptor's
    dispatch targets. The UI descriptor generator itself never introspects
    those concrete subclasses — it resolves labels for its own dispatch
    targets (the bare Tier 1 mixin and the physical-item mixin that is_a's it)
    via _get_class_label_annotations' ancestor walk, independent of whatever
    the concrete subclass carries."""
    gen = UiDescriptorGenerator(SCHEMA_PATH, top_class="DonationItem")

    bare = gen._get_class_label_annotations("FurnitureCategory")
    physical = gen._get_class_label_annotations("FurnitureAssessmentMixin")
    assert bare.get("label_en").value == "Furniture"
    assert physical.get("label_en").value == "Furniture"
    assert bare.get("label_de").value == physical.get("label_de").value == "Möbel"

    # A category with no Tier 2 split still resolves for both its own bare
    # mixin and its trivial physical-item composition class.
    clothing_bare = gen._get_class_label_annotations("ClothingCategory")
    clothing_physical = gen._get_class_label_annotations("ClothingPhysicalItemMixin")
    assert clothing_bare.get("label_en").value == "Clothing"
    assert clothing_physical.get("label_en").value == "Clothing"

    # DonationItem's real concrete subclasses carry the same label, kept in
    # sync with their Tier 1 mixin, for alias_generator.py's benefit.
    sv = SchemaView(SCHEMA_PATH)
    clothing_item_cls = sv.get_class("ClothingItem")
    clothing_item_anns = getattr(clothing_item_cls, "annotations", None) or {}
    assert clothing_item_anns.get("label_en").value == "Clothing"


CATEGORY_VALUE_TO_EXPECTED_LABEL_EN = {
    "ClothingItem": "Clothing",
    "AccessoriesItem": "Accessories",
    "FootwearItem": "Footwear",
    "FurnitureItem": "Furniture",
    "BeddingTextilesItem": "Bedding and Textiles",
    "HouseholdItem": "Household",
    "ElectronicsItem": "Electronics",
    "ToysItem": "Toys and Games",
    "SportsItem": "Sports",
    "BooksItem": "Books",
    "StationeryItem": "Stationery",
    "PersonalCareItem": "Personal Care",
    "MobilityAidsItem": "Mobility Aids and Assistive Devices",
    "BabyInfantItem": "Baby and Infant Supplies",
    "FoodItem": "Food",
    "OtherItem": "Other",
}


def test_ui_descriptor_category_enum_values_resolve_labels_via_same_named_class():
    """BaseCategoryEnum/SortingCategoryEnum permissible values (e.g.
    "ClothingItem") carry only dispatch_to — no label_en/label_de of their
    own, by design, to avoid a third copy of the translation alongside the
    Tier 1 mixin and the DonationItem subclass. _collect_labels must resolve
    each category value's label by falling back to the real DonationItem
    subclass of the same name (ancestor-walked up to its Tier 1 mixin),
    not silently echo the raw enum value name back as the label."""
    sv = SchemaView(SCHEMA_PATH)
    for enum_name in ("BaseCategoryEnum", "SortingCategoryEnum"):
        enum_def = sv.get_enum(enum_name)
        for value in CATEGORY_VALUE_TO_EXPECTED_LABEL_EN:
            pv = enum_def.permissible_values[value]
            anns = getattr(pv, "annotations", None) or {}
            assert "label_en" not in anns, (
                f"{enum_name}.{value} unexpectedly carries its own label_en — "
                "update CATEGORY_VALUE_TO_EXPECTED_LABEL_EN / this test's "
                "premise if that was intentional"
            )

    donation_gen = UiDescriptorGenerator(SCHEMA_PATH, top_class="DonationItem")
    donation_labels_en = donation_gen._collect_labels(
        {"DonationItem": donation_gen._build_descriptor("DonationItem")}, "en"
    )
    demand_gen = UiDescriptorGenerator(SCHEMA_PATH, top_class="DemandSignal")
    demand_labels_en = demand_gen._collect_labels(
        {"DemandSignal": demand_gen._build_descriptor("DemandSignal")}, "en"
    )

    for value, expected in CATEGORY_VALUE_TO_EXPECTED_LABEL_EN.items():
        assert donation_labels_en.get(value) == expected, (
            f"DonationItem (SortingCategoryEnum): {value} -> "
            f"{donation_labels_en.get(value)!r}, expected {expected!r}"
        )
        assert demand_labels_en.get(value) == expected, (
            f"DemandSignal (BaseCategoryEnum): {value} -> "
            f"{demand_labels_en.get(value)!r}, expected {expected!r}"
        )


def test_ui_descriptor_dispatch_is_schema_driven_via_enum_annotations():
    """Dispatch is triggered purely by schema content — a slot whose range
    is an enum carrying dispatch_to annotations on its permissible values —
    not by designates_type (dropped from all four roots; the generated
    Python data model isn't in use, so there's no reason to accept its
    real-subclass-polymorphism trade-off) and not by any root-name check in
    the generator. Confirm both dispatch enums resolve correctly and
    on-enum-content alone determines bare vs. physical-item targets."""
    sv = SchemaView(SCHEMA_PATH)
    for cls in ("DonationItem", "StorageCollection", "SortedCollection", "DemandSignal"):
        cat_slot = sv.induced_slot("category", cls)
        assert not getattr(cat_slot, "designates_type", False), (
            f"{cls}.category still has designates_type set"
        )

    donation = UiDescriptorGenerator(SCHEMA_PATH, top_class="DonationItem")
    donation_cat_slot = donation.schemaview.induced_slot("category", "DonationItem")
    assert donation_cat_slot.range == "SortingCategoryEnum"
    dispatch_enum = donation._get_dispatch_enum(donation_cat_slot)
    assert dispatch_enum is not None
    assert dispatch_enum.name == "SortingCategoryEnum"

    demand = UiDescriptorGenerator(SCHEMA_PATH, top_class="DemandSignal")
    demand_cat_slot = demand.schemaview.induced_slot("category", "DemandSignal")
    assert demand_cat_slot.range == "BaseCategoryEnum"
    demand_dispatch_enum = demand._get_dispatch_enum(demand_cat_slot)
    assert demand_dispatch_enum.name == "BaseCategoryEnum"

    # A slot with a plain, non-dispatch enum range must not be mistaken for
    # a dispatch slot.
    usage_slot = donation.schemaview.induced_slot("usage", "DonationItem")
    assert donation._get_dispatch_enum(usage_slot) is None


def _generate(top_class):
    return UiDescriptorGenerator(SCHEMA_PATH, top_class=top_class).generate()[top_class]


def _dispatch_map(root_descriptor):
    return next(f for f in root_descriptor["fields"] if f["name"] == "category")["dispatches_to"]


def test_ui_descriptor_sorted_collection_and_donation_item_share_physical_item_files():
    """SortedCollection and DonationItem both use SortingCategoryEnum for
    their category slot, so they must dispatch to the exact same
    physical-item files per category — that's the entire point of the
    shared-file design, not per-root duplicates."""
    sorted_ = _generate("SortedCollection")
    donation = _generate("DonationItem")

    sorted_map = _dispatch_map(sorted_)
    donation_map = _dispatch_map(donation)

    assert len(sorted_map) == 16
    assert sorted_map == donation_map
    assert all(v.endswith(("AssessmentMixin.ui.json", "PhysicalItemMixin.ui.json")) for v in sorted_map.values())

    # Root-owned fields never appear in the shared category files.
    furniture = _generate("FurnitureAssessmentMixin")
    field_names = {f["name"] for f in furniture["fields"]}
    assert "usage" not in field_names
    assert "donation_source" not in field_names
    assert "sorting_notes" not in field_names
    assert "assessment_result" in field_names  # category-owned, correctly present


def test_ui_descriptor_storage_collection_and_demand_signal_share_bare_files():
    """StorageCollection uses BaseCategoryEnum for its category slot — the
    same enum DemandSignal uses — so both dispatch to the bare Tier 1
    category files, not the physical-item files SortedCollection/DonationItem
    use. StorageCollection therefore does NOT share dispatch targets with
    SortedCollection/DonationItem."""
    storage = _generate("StorageCollection")
    demand = _generate("DemandSignal")
    sorted_ = _generate("SortedCollection")

    storage_map = _dispatch_map(storage)
    demand_map = _dispatch_map(demand)
    sorted_map = _dispatch_map(sorted_)

    assert len(storage_map) == 16
    assert storage_map == demand_map
    assert storage_map != sorted_map
    assert all(
        v.endswith("Category.ui.json") and "Assessment" not in v and "PhysicalItem" not in v
        for v in storage_map.values()
    )


def test_ui_descriptor_storage_collection_root_fields():
    storage = _generate("StorageCollection")
    fields = {f["name"]: f for f in storage["fields"]}
    assert fields["usage"]["required_in_step"] is False
    assert fields["usage"]["completeness"] == "standard"
    assert fields["category"]["required_in_step"] is True
    assert fields["category"]["completeness"] == "minimal"


def test_ui_descriptor_sorted_collection_root_fields():
    sorted_ = _generate("SortedCollection")
    fields = {f["name"]: f for f in sorted_["fields"]}
    assert fields["usage"]["required_in_step"] is True
    assert fields["usage"]["completeness"] == "minimal"
    assert fields["category"]["required_in_step"] is True
    assert fields["category"]["completeness"] == "minimal"


def test_ui_descriptor_demand_signal_structure():
    """DemandSignal dispatches to bare Tier 1 files only: no assessment_result
    anywhere, no lc-*-derived visible_when anywhere, and the
    PersonalCareSubcategoryEnum drift the design doc flagged is resolved
    automatically since DemandSignal now reuses the one canonical enum."""
    demand = _generate("DemandSignal")
    dispatch_map = _dispatch_map(demand)
    assert len(dispatch_map) == 16

    sv = SchemaView(SCHEMA_PATH)
    assert sv.get_class("AnyValue") is None

    for category_value, filename in dispatch_map.items():
        target_class = filename.removesuffix(".ui.json")
        target = _generate(target_class)
        for field in target["fields"]:
            assert field["name"] != "assessment_result", (
                f"DemandSignal's {category_value} dispatch target unexpectedly "
                f"has assessment_result"
            )
            visible_when = field.get("visible_when", {})
            assert "lifecycle_state" not in visible_when, (
                f"DemandSignal's {category_value}.{field['name']} unexpectedly "
                f"has lifecycle_state-gated visibility"
            )

    personal_care = _generate("PersonalCareCategory")
    subcategory_values = personal_care["enums"]["PersonalCareSubcategoryEnum"]
    assert "sanitary_products" in subcategory_values
    assert "incontinence_products" in subcategory_values
    assert "nappies_incontinence" not in subcategory_values
